version: '3'

services:
  summarizer:
    build: ./services
    image: summarizer
    container_name: summarizer
    volumes:
      - ${SUMMARIZATION_PROJECT_ROOT}:/app
      - ./log/summarization:/log
      - ./services/summarization/run.sh:/run.sh:ro
    environment:
      - FLASK_APP=${FLASK_APP}
      - RUN_APP=${RUN_APP}
      - FLASK_PORT=${FLASK_PORT}
      - SUPERVISOR_LOG_FILE=${SUPERVISOR_LOG_FILE}
      - GUNICORN_LOG_FILE=${GUNICORN_LOG_FILE}
      - GUNIKORN_LOG_LEVEL=${GUNIKORN_LOG_LEVEL}
      - GUNICORN_WORKERS_COUNT=${GUNICORN_WORKERS_COUNT}
      - GUNIKORN_TIMEOUT=${GUNIKORN_TIMEOUT}
      - SUMMARIZATION_API_URL=${SUMMARIZATION_API_URL}
      - ENV=prod
    command: sh /run.sh
    networks:
      - network
    ports:
      - 5000:5000
    restart: unless-stopped
networks:
  network:
volumes:
  nvidia_driver:
    external: true
